// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyContext;

namespace MyContext.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20210618181015_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyContext.Quote", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AnotherQuotePropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuotePropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SomeQuoteData")
                        .HasColumnType("int");

                    b.HasKey("QuoteId");

                    b.HasIndex("AnotherQuotePropertyId");

                    b.HasIndex("QuotePropertyId");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("MyContext.QuoteProperty", b =>
                {
                    b.Property<Guid>("QuotePropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SomeQuotePropertyData")
                        .HasColumnType("int");

                    b.HasKey("QuotePropertyId");

                    b.ToTable("QuoteProperties");
                });

            modelBuilder.Entity("MyContext.Quote", b =>
                {
                    b.HasOne("MyContext.QuoteProperty", "AnotherQuoteProperty")
                        .WithMany()
                        .HasForeignKey("AnotherQuotePropertyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyContext.QuoteProperty", "QuoteProperty")
                        .WithMany()
                        .HasForeignKey("QuotePropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnotherQuoteProperty");

                    b.Navigation("QuoteProperty");
                });
#pragma warning restore 612, 618
        }
    }
}
